### ISSUE TITLE
Maven site link not working Information about the project

### ISSUE THREAD

**Issue by Markpeter** [bitzeche/zencoder-java#12]
Maven site: here (Information about this project) is not working.  shows - Not Found

The requested URL /svn/tags/zencoder-api-0.9.2/site/index.html was not found on this server.

Kindly update it.

**Comment by drallgood** [comment]
Yep. You're right. I'll fix it with 0.9.3

**Comment by drallgood** [comment]
fixed in 0.9.4

URL is http://bitzeche.github.io/zencoder-java/
