### ISSUE TITLE
need some demo or some step by step procedures to use this zencoder api

### ISSUE THREAD

**Issue by Markpeter** [bitzeche/zencoder-java#15]
Hi i was searching deeply how to use this zencoder but nope i didn't get any info can you provide some demo or step by step procedures to describe how to use this. Hoping for your best

**Comment by aleksey-korolev** [comment]
This project is java implementation of zencoder.com video service API. To get general idea how to use zencoder video service visit zencoder.com. If you are sure you need this java implementation of zencoder API you need to create a maven project and add dependency to this project's library like this:
groupId de.bitzeche.video.transcoding
artifactId zencoder-api
0.9.3-SNAPSHOT

**Comment by Markpeter** [comment]
Thanks  for you reply aleksey-korolev . i had downloaded the this java implementation of zencoder API  and with help of Netbeans IDE i downloaded the maven repositories in the file "ZencoderClientTest.java" i changed the API key and built it. It shows me All test passed but when i view it in " https://app.zencoder.com/api_requests " for API Request history it shows me " 422 Unprocessable " error am not understanding the error. kindly tell me am in right path and provide me some steps or procedures to implement it in detail. Also i want to know do we have any forums for zencoder to clear the doubts. suggest me something that you can

**Comment by aleksey-korolev** [comment]
If you were able to submit API request then you are on the right path. I don't know of any zencoder replaced forums, but their documentation is quite good: https://app.zencoder.com/docs - and their support responds rapidly, just specify your job id along with your question.

**Comment by drallgood** [comment]
"Unprocessable" probably means, your file wasn't valid/couldn't be processed by the zencoder servers.

**Comment by Markpeter** [comment]
I think its not invalid because i used the same link (http://ca.bitzeche.de/big_buck_bunny_720p_h264.mov) given by default in java implementation of zencoder API

**Comment by Markpeter** [comment]
Also am getting this following info in log does this problem makes me to give error like i said above,

---

 "Some problems were encountered while building the effective model for de.bitzeche.video.transcoding:zencoder - api:jar:0.9.3-SNAPSHOT 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 120, column 12

It is highly recommended to fix these problems because they threaten the stability of your build.

For this reason, future Maven versions might no longer support building such malformed projects.

[pool-1-thread-1] ERROR d.b.v.t.zencoder.ZencoderClient - couldn't submit job: Url of input file has an invalid protocol

---

and the line 120 contains the info i attached in image
![Line 120](https://f.cloud.github.com/assets/1962939/18983/5a78e032-48f2-11e2-80df-98cad1e71a7e.png)
,

When i Test the API i got the Test Results as "100 % Passed ". 
Kindly suggest me how to solve it.

**Comment by drallgood** [comment]
I've kicked off an new build on our build system and everything worked as expected. 
No "unprocessable" jobs here. The account is running in Integration mode, though.

**Comment by Markpeter** [comment]
Mine too integration mode only drailgood. If you want to see whats the problem and where the problem is jus use Netbeans IDE and import the api and test it you can see the log test as 100% passed and with the above problems listed.

Just noted, even though i get the above problems i can see the job finished for the " Bugs bunny" movie. But if give a test audio file it gets cancelled automatically cant get what problem. Do you have any idea. do i need to do anything in code if i use audio link. Kindly suggest me.

**Comment by drallgood** [comment]
Those maven messages can be ignored. They really don't mean much.

**Comment by Markpeter** [comment]
ok fine then what about the audio file i just added the link nothing changed in code but getting cancelled in encoder

**Comment by drallgood** [comment]
I guess there's something wrong with your request (as the tests are configured to work with video files).
You should see the XML request in your logs. Could you please post it?

**Comment by Markpeter** [comment]
Thank you drailgood. This is what am getting in log,

![xml](https://f.cloud.github.com/assets/1962939/19250/042cad5a-4909-11e2-8fa3-24b9fad4bf98.png)

**Comment by drallgood** [comment]
Yep, that's supposed to fail.
Our tests are checking for several things that could go wrong, one of them being that the protocol specified in the URL is invalid.

**Comment by Markpeter** [comment]
So you mean i cant use the audio processing with this java implementation of zencoder right?

**Comment by drallgood** [comment]
Quite the opposite.
Of course you can process audio with zencoder using this java client.

The tests you are running are just testing different things. Some of them will fail as they are supposed to. There is nothing wrong with it.
In fact, if you look at your Zencoder Dashboard, you should see several cancelled and a few completed tests.

On my side, it looks like this:

![Screen Shot 2012-12-18 at 1 38 30 PM](https://f.cloud.github.com/assets/127142/19358/eb0401aa-490f-11e2-99af-de33b6958958.png)

**Comment by Markpeter** [comment]
ok so if i get cancelled for a job can i again retry the job from this java client. where i have to configure for that

**Comment by drallgood** [comment]
Nowhere. The job isn't cancelled by itself. Someone has to request that.
Our tests are doing it, but your code might not.

I think you are mixing a few things up. Tests are intended for testing the implementation, not for being used as implementation.

**Comment by drallgood** [comment]
You can, however resubmit the job using the resubmit method in our API.

**Comment by Markpeter** [comment]
Thanks A lot drailgood. i need your support for these kind of issues as we don't have any forums to post. Shall i post my future doubts under the issue category in this project else do we have any forums to discuss it. Kindly provide me some info for it

**Comment by drallgood** [comment]
There is no forum for this project at the moment, but I could create a mailing list if there is need for one.
