### ISSUE TITLE
What is the String "S" meant here

### ISSUE THREAD

**Issue by Markpeter** [bitzeche/zencoder-java#16]
What is the String "S" meant here in the line,

ZencoderJob job = new ZencoderJob("s" + TEST_VIDEO_URL);

from the below code in the file "ZencoderClientTest.java"

@Test(dataProvider = "ApiVersionDS", expectedExceptions = ZencoderErrorResponseException.class)
    public void createJobAndProduceErrorWithMalformedVideoURL(
            ApiVersionProvider provider) throws ZencoderErrorResponseException {
        ZencoderAPIVersion apiVersion = provider.getApiVersion();
        IZencoderClient client = createClient(apiVersion);
        ZencoderJob job = new ZencoderJob("s" + TEST_VIDEO_URL);
        job.setZencoderRegion(ZENCODER_REGION);
        job.setTest(true);
        client.createJob(job);
    }

**Comment by drallgood** [comment]
Oh, pretty easy. 
Adding the 's' to an (otherwise valid) URL creates one with an invalid protocol ("shttp" doesn't exist) which then triggers an exception.
