### ISSUE TITLE
how to deploy the zencoder-java in eclipse.

### ISSUE THREAD

**Issue by Markpeter** [bitzeche/zencoder-java#17]
Can you tell me how to deploy this zencoder-java in eclipse project. i tried it to deploy but failed

**Comment by drallgood** [comment]
That depends on the nature of your project.
The easiest way is to have a maven project and just define it as a dependency (as documented https://github.com/bitzeche/zencoder-java/wiki).

**Comment by Markpeter** [comment]
That's good.  Can you tell me whether i have to pass the URL link (only) to the TEST_VIDEO_URL in ZencoderClientTest.java or is it possible to send the byte of arrays of an video input.

I tried the local path in this TEST_VIDEO_URL as TEST_VIDEO_URL= "c:/zencodervideo/sample.mp4   but when run it the encoder process gets failed in the server side. 

So do i always need to give an input as a URL link ?

**Comment by drallgood** [comment]
As the Zencoder servers have to access your file in order to process it, it needs to be an URL. E.g. either public/password protected on your server or on S3.
Details can be found here: https://app.zencoder.com/docs/api/encoding/job/input
