### ISSUE TITLE
How to Send a array of URL's or a Group of URL links in the zencoder

### ISSUE THREAD

**Issue by Markpeter** [bitzeche/zencoder-java#18]
I can test the single URL link every time in the zencoder using the String TEST_VIDEO_URL . If i want to send a group of URLs or an Array of URLs in the zencoder, is it possible to do it. How can i achieve it. 

Kindly suggest me an idea.

**Comment by drallgood** [comment]
What exactly do you want to do?
Create a test with multiple input files?

**Comment by Markpeter** [comment]
I want to send some list of URL's to be encoded say example: i have the following URL's to be encoded, 
www.myexample.com/tone1.mp3;
www.myexample.com/tone2.mp3;
www.myexample.com/tone3.mp3;
www.myexample.com/tone4.mp3;
www.myexample.com/tone5.mp3; 

The how can i pass all these 5 files to zencoder together instead of one by one.

**Comment by drallgood** [comment]
Sorry, there is no way of doing that in one job. Zencoder itself only supports one input per job, so we can't do anything to change that.

What you can do is create multiple jobs (each with one of the URLs) and submit them one by one.
