### ISSUE TITLE
Security Exception after adding the code as given in wiki implement of zencoder Java

### ISSUE THREAD

**Issue by Markpeter** [bitzeche/zencoder-java#20]
When i implement the code given in Wiki and tested it, rises the exception of access denied.
The line " (zencode.java:63) "  contains the code " client.createJob(job); " 

Can you tell me how to solve this issue.

It starts the XML process like this,
<code>  api-request 
     [java]   input  http://myurl.com/demo/tone.mp3  /input 
     [java]    download_connections 5 /download_connections 
     [java]    test 1 /test 
     [java]    private 0 /private 
     [java]    api_key 7e76f37543c0e6ce69af113e6d8581c9 /api_key 
     [java]  /api-request  </code>

After this line it debugs like this,

[java] 16:19:37.711 [1835465145@qtp-458872080-0] DEBUG o.a.c.h.params.DefaultHttpParams - Set parameter http.protocol.cookie-policy = ignoreCookies
     [java] 16:19:37.711 [1835465145@qtp-458872080-0] DEBUG o.a.c.h.params.DefaultHttpParams - Set parameter http.authentication.credential-provider = null

then it rises the exception  like this,

java.security.AccessControlException: access denied (java.lang.RuntimePermission modifyThreadGroup)

[java] com.sun.jersey.api.client.ClientHandlerException: java.security.AccessControlException: access denied (java.lang.RuntimePermission modifyThreadGroup)
     [java]     at com.sun.jersey.client.apache.ApacheHttpClientHandler.handle(ApacheHttpClientHandler.java:266)
     [java]     at com.sun.jersey.api.client.Client.handle(Client.java:616)
     [java]     at com.sun.jersey.api.client.WebResource.handle(WebResource.java:559)
     [java]     at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:72)
     [java]     at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:502)
     [java]     at de.bitzeche.video.transcoding.zencoder.ZencoderClient.sendPostRequest(ZencoderClient.java:313)
     [java]     at de.bitzeche.video.transcoding.zencoder.ZencoderClient.createJob(ZencoderClient.java:168)
     [java]     at com.model.zencode.processRequest(zencode.java:44)
     [java]     at com.model.zencode.doGet(zencode.java:63)

**Comment by drallgood** [comment]
Are you, by any chance, running this on GWT? I've found a lot of reports on google, that this Exceptions occur when using GWT.

**Comment by Markpeter** [comment]
NO am not using the GWT in my application. I just try to send the file to zencoder through the Java API and facing this problem. Even i had created a Keytool for certificate validation but later on this it shows exception like 401 unauthorized access.

**Comment by Markpeter** [comment]
Any Idea's drail??

**Comment by drallgood** [comment]
Not really... Sounds like a java permissions thing, but I have never encountered this particular exception.
Sorry.

**Comment by Markpeter** [comment]
No probs let me solve and update you. If you get any ideas about it kindly let me know it.

**Comment by Markpeter** [comment]
drail can you send me a sample accessing zencoder in jsp or servlet. As you said you didn't encountered problem like this I can verify with my code and let you know what problem it is.

**Comment by Markpeter** [comment]
Drail, I got reason of this exception. Its due to Google App engine server. As am using Google App engine server for my application(GAE) its not accepting the jersey client so the error comes here " client.createJob(job); " . When i checked the same application in Apache Tomcat Server it executes successfully. Do you have any idea to solve the jersey issue in GAE for zencoder Java API

**Comment by drallgood** [comment]
Not really. I googled around quite a bit and from what I could grasp the only option seems to be to replace jersey with something else.

**Comment by drallgood** [comment]
I'm looking into this issue right now, but I'll need your help to test a few possible solutions.

**Comment by drallgood** [comment]
I've just pushed a change (should be deployed in a few minutes) that could help you fix this issue.

What I'm trying to do is to provide you an option to use a Single-threaded client instead of the default multi-threaded one.

Try this:

> HttpClient client = new HttpClient(new SimpleHttpConnectionManager());
> ApacheHttpClientHandler apacheHttpClientHandler = new ApacheHttpClientHandler(client, new DefaultApacheHttpClientConfig());
> ApacheHttpClient httpClient = new ApacheHttpClient(apacheHttpClientHandler);
> zencoderClient.setHttpClient(httpClient);

**Note:** The setter isn't included in the IZencoderClient Interface as this is a implementation specific issue.

**Comment by Markpeter** [comment]
Thanks a lot for your support drail and ill surely help you to test the possibilities. Can you tell me where exactly i want to add the code you mentioned above.

**Comment by drallgood** [comment]
Wherever you are initializing the ZencoderClient.

**Comment by drallgood** [comment]
Did you manage to fix this issue?
