### ISSUE TITLE
Move Maven repo to github

### ISSUE THREAD

**Issue by xuan** [bitzeche/zencoder-java#3]
I've forked your project and have made some small modification.   I created a maven repo using the following guide:  http://chkal.blogspot.com/2010/09/maven-repositories-on-github.html and have a github repo at http://xuan.github.com/zencoder-java/repository/

You may consider doing the same for other people who may want to use it.

**Comment by drallgood** [comment]
We have our own, dedicated repository running at http://trac.bitzeche.de/archiva/ :

Snapshots are here: http://trac.bitzeche.de/archiva/repository/snapshots/
Releases will be here: http://trac.bitzeche.de/archiva/repository/release/
