### ISSUE TITLE
NumberFormatException in ZencoderClient when parsing error response from server

### ISSUE THREAD

**Issue by aleksey-korolev** [bitzeche/zencoder-java#7]
Use ZencoderClient.createJob() to submit encoding job.
If malformed video url is submitted zencoder.com returns XML with error description:

``` xml
<?xml version=1.0 encoding=UTF-8?>
<api-response>
  <errors type=array>
    <error>Url must include a file name</error>
    <error>Url of input file is invalid</error>
    <error>Url of input file is not well formed. Please confirm that it is a valid URL.</error>
  </errors>
</api-response>
```

ZencoderClient.createJob method attempts to parse job id from the response and fails with NumberFormatException. It would be nice if ZencoderClient would detect error in response, parse response and return error details.

**Comment by drallgood** [comment]
Yep.. That's unfortunate. I'll have a look into it, as soon as I have time for it.
