### ISSUE TITLE
Add job progress implementation

### ISSUE THREAD

**Issue by aleksey-korolev** [bitzeche/zencoder-java#8]
Related Zencoder documentation page: https://app.zencoder.com/docs/api/jobs/progress

As an API user I'd like to have both domain object and a request method in IZencoderClient, e.g. IZencoderClient.getJobProgress(int jobId)

**Comment by drallgood** [comment]
Thanks for your report.
James has already implemented this in our 0.9.3a branch. I've merged it into the master now.

**Comment by aleksey-korolev** [comment]
Great, when do you plan 0.9.3 release?

**Comment by drallgood** [comment]
Can't tell you an exact date, but you can use the nightly snapshot release until then if you like,
