### ISSUE TITLE
Hardcoded Zencoder DEV api URL is used to submit jobs

### ISSUE THREAD

**Issue by aleksey-korolev** [bitzeche/zencoder-java#9]
ZencoderClient constructor accepts one of 3 api URL options from ZencoderAPIVersion enum which is used later to perform requests to Zencoder during ZencoderClient object's lifetime.

ZencoderClient.createJob() method doesn't use corresponding parameter passed to constructor, instead it sends request to https://app.zencoder.com/api/ (DEV api).

**Comment by drallgood** [comment]
Thanks for reporting this.
There's actually already a fix for that in one of our branches (0.9.3a). I've merged it into our master branch.

**Comment by aleksey-korolev** [comment]
cool, thanks!
